Make log message more obvious
ondrejbartas/sidekiq-cron pull request #305
Opened 2021-06-09 13:54 UTC by arrrnas

`Cron Jobs - add job with name:` seemed like a warning that some action needs to be taken ¯\\_(ツ)\_/¯

2021-09-04 23:59 UTC, Wittiest approved these changes

2021-12-15 07:51 UTC, TALlama approved these changes
@ondrejbartas This PR matches the "deleted job" message on the other side. Looks good to me.

2022-03-15 00:21 UTC, mathieujobin requested changes
i don't see a benefit outside potentially breaking parsing

2022-04-11 19:52 UTC, markets commented
@ondrejbartas @honzasterba what do you think about this one? 

I understand @mathieujobin's concern, but consistency is also good!

2022-04-11 20:42 UTC, honzasterba commented
Looks good to me.

I don't think log messages should be treated as API.

2022-04-11 20:42 UTC, honzasterba approved these changes

2022-04-11 21:06 UTC, merged